_wandb:
    value:
        cli_version: 0.17.2
        python_version: 3.10.12
        t:
            1:
                - 55
            2:
                - 55
            3:
                - 16
                - 23
                - 55
            4: 3.10.12
            5: 0.17.2
            8:
                - 5
            12: 0.17.2
            13: linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
